# Generated by Django 2.1 on 2018-09-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkins', '0002_auto_20180910_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkins',
            name='place_name',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
